-- Card catalog seed data for Boundaries Crossed set
TRUNCATE boundaries_crossed RESTART IDENTITY CASCADE;

INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (1, 'Oddish', '/media/sets/Boundaries_Crossed/1.jpg', 0.27);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (2, 'Gloom', '/media/sets/Boundaries_Crossed/2.jpg', 0.31);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (3, 'Vileplume', '/media/sets/Boundaries_Crossed/3.jpg', 1.81);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (4, 'Bellossom', '/media/sets/Boundaries_Crossed/4.jpg', 0.49);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (5, 'Tangela', '/media/sets/Boundaries_Crossed/5.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (6, 'Tangrowth', '/media/sets/Boundaries_Crossed/6.jpg', 1.06);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (7, 'Scyther', '/media/sets/Boundaries_Crossed/7.jpg', 0.79);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (8, 'Heracross', '/media/sets/Boundaries_Crossed/8.jpg', 0.79);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (9, 'Celebi-EX', '/media/sets/Boundaries_Crossed/9.jpg', 13.48);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (10, 'Shaymin', '/media/sets/Boundaries_Crossed/10.jpg', 1.21);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (11, 'Snivy', '/media/sets/Boundaries_Crossed/11.jpg', 0.21);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (12, 'Servine', '/media/sets/Boundaries_Crossed/12.jpg', 0.63);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (13, 'Serperior', '/media/sets/Boundaries_Crossed/13.jpg', 3.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (14, 'Cottonee', '/media/sets/Boundaries_Crossed/14.jpg', 0.28);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (15, 'Whimsicott', '/media/sets/Boundaries_Crossed/15.jpg', 0.41);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (16, 'Petilil', '/media/sets/Boundaries_Crossed/16.jpg', 0.38);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (17, 'Lilligant', '/media/sets/Boundaries_Crossed/17.jpg', 0.42);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (18, 'Charmander', '/media/sets/Boundaries_Crossed/18.jpg', 1.75);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (19, 'Charmeleon', '/media/sets/Boundaries_Crossed/19.jpg', 0.92);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (20, 'Charizard', '/media/sets/Boundaries_Crossed/20.jpg', 23.67);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (21, 'Numel', '/media/sets/Boundaries_Crossed/21.jpg', 0.11);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (22, 'Camerupt', '/media/sets/Boundaries_Crossed/22.jpg', 0.21);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (23, 'Victini', '/media/sets/Boundaries_Crossed/23.jpg', 0.39);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (24, 'Tepig', '/media/sets/Boundaries_Crossed/24.jpg', 0.38);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (25, 'Pignite', '/media/sets/Boundaries_Crossed/25.jpg', 0.71);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (26, 'Emboar', '/media/sets/Boundaries_Crossed/26.jpg', 3.07);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (27, 'Darumaka', '/media/sets/Boundaries_Crossed/27.jpg', 0.17);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (28, 'Darmanitan', '/media/sets/Boundaries_Crossed/28.jpg', 0.39);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (29, 'Squirtle', '/media/sets/Boundaries_Crossed/29.jpg', 1.14);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (30, 'Wartortle', '/media/sets/Boundaries_Crossed/30.jpg', 0.27);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (31, 'Blastoise', '/media/sets/Boundaries_Crossed/31.jpg', 13.50);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (32, 'Psyduck', '/media/sets/Boundaries_Crossed/32.jpg', 1.48);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (33, 'Psyduck', '/media/sets/Boundaries_Crossed/33.jpg', 0.44);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (34, 'Golduck', '/media/sets/Boundaries_Crossed/34.jpg', 0.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (35, 'Golduck', '/media/sets/Boundaries_Crossed/35.jpg', 0.31);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (36, 'Marill', '/media/sets/Boundaries_Crossed/36.jpg', 0.41);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (37, 'Azumarill', '/media/sets/Boundaries_Crossed/37.jpg', 0.33);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (38, 'Delibird', '/media/sets/Boundaries_Crossed/38.jpg', 0.27);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (39, 'Oshawott', '/media/sets/Boundaries_Crossed/39.jpg', 0.29);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (40, 'Dewott', '/media/sets/Boundaries_Crossed/40.jpg', 0.56);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (41, 'Samurott', '/media/sets/Boundaries_Crossed/41.jpg', 1.51);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (42, 'Ducklett', '/media/sets/Boundaries_Crossed/42.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (43, 'Swanna', '/media/sets/Boundaries_Crossed/43.jpg', 0.30);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (44, 'Frillish', '/media/sets/Boundaries_Crossed/44.jpg', 0.22);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (45, 'Jellicent', '/media/sets/Boundaries_Crossed/45.jpg', 0.55);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (46, 'Cryogonal', '/media/sets/Boundaries_Crossed/46.jpg', 0.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (47, 'Keldeo', '/media/sets/Boundaries_Crossed/47.jpg', 0.87);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (48, 'Keldeo', '/media/sets/Boundaries_Crossed/48.jpg', 0.33);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (49, 'Keldeo-EX', '/media/sets/Boundaries_Crossed/49.jpg', 0.92);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (50, 'Pikachu', '/media/sets/Boundaries_Crossed/50.jpg', 1.48);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (51, 'Voltorb', '/media/sets/Boundaries_Crossed/51.jpg', 0.16);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (52, 'Electrode', '/media/sets/Boundaries_Crossed/52.jpg', 0.17);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (53, 'Electabuzz', '/media/sets/Boundaries_Crossed/53.jpg', 0.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (54, 'Electivire', '/media/sets/Boundaries_Crossed/54.jpg', 1.07);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (55, 'Chinchou', '/media/sets/Boundaries_Crossed/55.jpg', 0.22);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (56, 'Blitzle', '/media/sets/Boundaries_Crossed/56.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (57, 'Zebstrika', '/media/sets/Boundaries_Crossed/57.jpg', 1.77);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (58, 'Wobbuffet', '/media/sets/Boundaries_Crossed/58.jpg', 0.51);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (59, 'Spoink', '/media/sets/Boundaries_Crossed/59.jpg', 0.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (60, 'Grumpig', '/media/sets/Boundaries_Crossed/60.jpg', 0.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (61, 'Duskull', '/media/sets/Boundaries_Crossed/61.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (62, 'Dusclops', '/media/sets/Boundaries_Crossed/62.jpg', 0.32);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (63, 'Dusknoir', '/media/sets/Boundaries_Crossed/63.jpg', 4.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (64, 'Croagunk', '/media/sets/Boundaries_Crossed/64.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (65, 'Croagunk', '/media/sets/Boundaries_Crossed/65.jpg', 0.32);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (66, 'Toxicroak', '/media/sets/Boundaries_Crossed/66.jpg', 0.44);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (67, 'Cresselia-EX', '/media/sets/Boundaries_Crossed/67.jpg', 7.12);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (68, 'Munna', '/media/sets/Boundaries_Crossed/68.jpg', 0.96);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (69, 'Musharna', '/media/sets/Boundaries_Crossed/69.jpg', 0.39);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (70, 'Woobat', '/media/sets/Boundaries_Crossed/70.jpg', 0.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (71, 'Swoobat', '/media/sets/Boundaries_Crossed/71.jpg', 0.37);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (72, 'Venipede', '/media/sets/Boundaries_Crossed/72.jpg', 0.30);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (73, 'Whirlipede', '/media/sets/Boundaries_Crossed/73.jpg', 0.38);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (74, 'Scolipede', '/media/sets/Boundaries_Crossed/74.jpg', 2.62);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (75, 'Gothita', '/media/sets/Boundaries_Crossed/75.jpg', 0.26);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (76, 'Gothorita', '/media/sets/Boundaries_Crossed/76.jpg', 0.26);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (77, 'Meloetta', '/media/sets/Boundaries_Crossed/77.jpg', 2.58);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (78, 'Sandshrew', '/media/sets/Boundaries_Crossed/78.jpg', 0.41);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (79, 'Sandslash', '/media/sets/Boundaries_Crossed/79.jpg', 0.47);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (80, 'Gligar', '/media/sets/Boundaries_Crossed/80.jpg', 0.15);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (81, 'Gliscor', '/media/sets/Boundaries_Crossed/81.jpg', 0.97);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (82, 'Makuhita', '/media/sets/Boundaries_Crossed/82.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (83, 'Trapinch', '/media/sets/Boundaries_Crossed/83.jpg', 0.29);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (84, 'Dwebble', '/media/sets/Boundaries_Crossed/84.jpg', 0.41);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (85, 'Crustle', '/media/sets/Boundaries_Crossed/85.jpg', 2.90);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (86, 'Mienfoo', '/media/sets/Boundaries_Crossed/86.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (87, 'Mienfoo', '/media/sets/Boundaries_Crossed/87.jpg', 0.29);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (88, 'Mienshao', '/media/sets/Boundaries_Crossed/88.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (89, 'Landorus-EX', '/media/sets/Boundaries_Crossed/89.jpg', 9.44);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (90, 'Purrloin', '/media/sets/Boundaries_Crossed/90.jpg', 0.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (91, 'Liepard', '/media/sets/Boundaries_Crossed/91.jpg', 2.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (92, 'Vullaby', '/media/sets/Boundaries_Crossed/92.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (93, 'Mandibuzz', '/media/sets/Boundaries_Crossed/93.jpg', 0.29);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (94, 'Scizor', '/media/sets/Boundaries_Crossed/94.jpg', 3.97);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (95, 'Skarmory', '/media/sets/Boundaries_Crossed/95.jpg', 0.27);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (96, 'Skarmory', '/media/sets/Boundaries_Crossed/96.jpg', 0.49);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (97, 'Klink', '/media/sets/Boundaries_Crossed/97.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (98, 'Vibrava', '/media/sets/Boundaries_Crossed/98.jpg', 0.40);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (99, 'Flygon', '/media/sets/Boundaries_Crossed/99.jpg', 2.94);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (100, 'Black Kyurem', '/media/sets/Boundaries_Crossed/100.jpg', 0.61);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (101, 'Black Kyurem-EX', '/media/sets/Boundaries_Crossed/101.jpg', 2.10);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (102, 'White Kyurem', '/media/sets/Boundaries_Crossed/102.jpg', 0.40);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (103, 'White Kyurem-EX', '/media/sets/Boundaries_Crossed/103.jpg', 1.79);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (104, 'Rattata', '/media/sets/Boundaries_Crossed/104.jpg', 0.39);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (105, 'Raticate', '/media/sets/Boundaries_Crossed/105.jpg', 2.95);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (106, 'Meowth', '/media/sets/Boundaries_Crossed/106.jpg', 0.34);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (107, 'Farfetch''d', '/media/sets/Boundaries_Crossed/107.jpg', 0.52);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (108, 'Ditto', '/media/sets/Boundaries_Crossed/108.jpg', 10.05);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (109, 'Snorlax', '/media/sets/Boundaries_Crossed/109.jpg', 1.30);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (110, 'Togepi', '/media/sets/Boundaries_Crossed/110.jpg', 1.17);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (111, 'Dunsparce', '/media/sets/Boundaries_Crossed/111.jpg', 0.26);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (112, 'Taillow', '/media/sets/Boundaries_Crossed/112.jpg', 0.22);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (113, 'Skitty', '/media/sets/Boundaries_Crossed/113.jpg', 0.30);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (114, 'Delcatty', '/media/sets/Boundaries_Crossed/114.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (115, 'Spinda', '/media/sets/Boundaries_Crossed/115.jpg', 0.27);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (116, 'Buneary', '/media/sets/Boundaries_Crossed/116.jpg', 0.35);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (117, 'Lopunny', '/media/sets/Boundaries_Crossed/117.jpg', 0.45);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (118, 'Patrat', '/media/sets/Boundaries_Crossed/118.jpg', 0.21);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (119, 'Watchog', '/media/sets/Boundaries_Crossed/119.jpg', 0.24);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (120, 'Lillipup', '/media/sets/Boundaries_Crossed/120.jpg', 0.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (121, 'Herdier', '/media/sets/Boundaries_Crossed/121.jpg', 0.26);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (122, 'Stoutland', '/media/sets/Boundaries_Crossed/122.jpg', 3.40);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (123, 'Pidove', '/media/sets/Boundaries_Crossed/123.jpg', 0.26);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (124, 'Tranquill', '/media/sets/Boundaries_Crossed/124.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (125, 'Unfezant', '/media/sets/Boundaries_Crossed/125.jpg', 0.43);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (126, 'Audino', '/media/sets/Boundaries_Crossed/126.jpg', 0.49);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (127, 'Aspertia City Gym', '/media/sets/Boundaries_Crossed/127.jpg', 0.28);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (128, 'Energy Search', '/media/sets/Boundaries_Crossed/128.jpg', 0.13);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (129, 'Great Ball', '/media/sets/Boundaries_Crossed/129.jpg', 0.19);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (130, 'Hugh', '/media/sets/Boundaries_Crossed/130.jpg', 0.20);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (131, 'Poké Ball', '/media/sets/Boundaries_Crossed/131.jpg', 0.19);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (132, 'Potion', '/media/sets/Boundaries_Crossed/132.jpg', 0.13);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (133, 'Rocky Helmet', '/media/sets/Boundaries_Crossed/133.jpg', 0.25);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (134, 'Skyla', '/media/sets/Boundaries_Crossed/134.jpg', 0.21);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (135, 'Switch', '/media/sets/Boundaries_Crossed/135.jpg', 0.15);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (136, 'Town Map', '/media/sets/Boundaries_Crossed/136.jpg', 3.57);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (137, 'Computer Search', '/media/sets/Boundaries_Crossed/137.jpg', 32.93);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (138, 'Crystal Edge', '/media/sets/Boundaries_Crossed/138.jpg', 1.91);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (139, 'Crystal Wall', '/media/sets/Boundaries_Crossed/139.jpg', 2.11);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (140, 'Gold Potion', '/media/sets/Boundaries_Crossed/140.jpg', 9.22);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (141, 'Celebi-EX', '/media/sets/Boundaries_Crossed/141.jpg', 54.58);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (142, 'Keldeo-EX', '/media/sets/Boundaries_Crossed/142.jpg', 40.46);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (143, 'Cresselia-EX', '/media/sets/Boundaries_Crossed/143.jpg', 30.93);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (144, 'Landorus-EX', '/media/sets/Boundaries_Crossed/144.jpg', 58.11);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (145, 'Black Kyurem-EX', '/media/sets/Boundaries_Crossed/145.jpg', 156.12);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (146, 'White Kyurem-EX', '/media/sets/Boundaries_Crossed/146.jpg', 128.99);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (147, 'Bianca', '/media/sets/Boundaries_Crossed/147.jpg', 199.99);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (148, 'Cheren', '/media/sets/Boundaries_Crossed/148.jpg', 64.57);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (149, 'Skyla', '/media/sets/Boundaries_Crossed/149.jpg', 215.23);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (150, 'Golurk', '/media/sets/Boundaries_Crossed/150.jpg', 111.80);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (151, 'Terrakion', '/media/sets/Boundaries_Crossed/151.jpg', 60.28);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (152, 'Altaria', '/media/sets/Boundaries_Crossed/152.jpg', 52.44);
INSERT INTO boundaries_crossed (id, name, image_path, price) VALUES (153, 'Rocky Helmet', '/media/sets/Boundaries_Crossed/153.jpg', 10.87);
